// Dev-only: snaps each route's rough waypoints to real pedestrian ways
// using the public OSRM foot-routing server, then bakes the result into
// src/data/paths.ts (consumed by src/data/routes.ts).
// Usage: node scripts/fetch-paths.ts
import { writeFileSync } from 'node:fs';
import { RAW_ROUTES as ROUTES } from '../src/data/routes.ts';

const OSRM = 'https://routing.openstreetmap.de/routed-foot/route/v1/foot/';

function haversine(a: [number, number], b: [number, number]): number {
  const R = 6371000;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b[1] - a[1]);
  const dLng = toRad(b[0] - a[0]);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a[1])) * Math.cos(toRad(b[1])) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

function snapToPath(
  coord: [number, number],
  path: [number, number][]
): [number, number] {
  let best = path[0];
  let bestD = Infinity;
  for (const p of path) {
    const d = haversine(coord, p);
    if (d < bestD) {
      bestD = d;
      best = p;
    }
  }
  return best;
}

const out: Record<
  string,
  { path: [number, number][]; checkpoints: [number, number][]; distanceM: number }
> = {};

async function main() {
for (const route of ROUTES) {
  // Route only through the landmarks; dense hand-drawn vertices snap to
  // random nearby ways and force long detours. Checkpoints flagged
  // via:false are display-only POIs and are skipped here.
  const waypoints: [number, number][] = [
    route.path[0],
    ...route.checkpoints.filter((cp) => cp.via !== false).map((cp) => cp.coord),
  ];
  const last = route.path[route.path.length - 1];
  const tail = waypoints[waypoints.length - 1];
  if (haversine(last, tail) > 50) waypoints.push(last);
  const coordStr = waypoints.map((c) => `${c[0]},${c[1]}`).join(';');
  // radiuses guard: refuse to snap an anchor further than 100m — a bigger
  // jump means the anchor is misplaced and the leg would wander off-route.
  const radiuses = waypoints.map(() => 100).join(';');
  const url = `${OSRM}${coordStr}?geometries=geojson&overview=full&steps=false&radiuses=${radiuses}`;
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`${route.id}: HTTP ${res.status}`);
    process.exit(1);
  }
  const json = (await res.json()) as any;
  if (json.code !== 'Ok' || !json.routes?.length) {
    console.error(
      `${route.id}: OSRM error ${json.code} — an anchor is probably >100m from any walkable way`
    );
    process.exit(1);
  }
  const path = json.routes[0].geometry.coordinates as [number, number][];
  const distanceM = json.routes[0].distance as number;

  // flag legs that detour badly compared to straight-line distance
  const snapped = json.waypoints.map((w: any) => w.location as [number, number]);
  json.routes[0].legs.forEach((leg: any, i: number) => {
    const straight = haversine(snapped[i], snapped[i + 1]);
    const ratio = straight > 0 ? leg.distance / straight : 1;
    if (leg.distance > 300 && ratio > 1.8) {
      console.warn(
        `  ⚠ ${route.id} leg ${i} (${waypoints[i]} → ${waypoints[i + 1]}): ` +
          `${Math.round(leg.distance)}m vs ${Math.round(straight)}m straight ` +
          `(x${ratio.toFixed(1)}) — check the anchors`
      );
    }
  });
  out[route.id] = {
    path,
    checkpoints: route.checkpoints.map((cp) => snapToPath(cp.coord, path)),
    distanceM,
  };
  console.log(
    `${route.id}: ${path.length} pts, ${(distanceM / 1000).toFixed(2)}km`
  );
  await new Promise((r) => setTimeout(r, 1200)); // be polite to the public server
}

const file = `// AUTO-GENERATED by scripts/fetch-paths.ts — do not edit by hand.
// Real pedestrian geometries snapped via OSRM foot routing (OSM data).
export interface BakedPath {
  path: [number, number][];
  checkpoints: [number, number][];
  distanceM: number;
}

export const BAKED: Record<string, BakedPath> = ${JSON.stringify(out)};
`;
writeFileSync('src/data/paths.ts', file);
console.log('src/data/paths.ts written');
}

main();
